In [3]:
import sklearn
import numpy as np
import pandas
import torch
import sklearn.datasets
import sklearn.preprocessing
import helpers
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import OneClassSVM
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, precision_score, recall_score, precision_recall_curve, roc_auc_score, f1_score, make_scorer, auc, average_precision_score

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Thyroid Dataset
Class 2 and 3 are Normal Data  
Class 1 is anomalous  
Analysis:
- Need to format these into 0 for normal data, 1 for anomalous
-

In [46]:
X_thyroid, Y_thyroid = helpers.load_thyroid_dataset()

In [47]:
X_thyroid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3772 non-null   float64
 1   1       3772 non-null   int64
 2   2       3772 non-null   int64
 3   3       3772 non-null   int64
 4   4       3772 non-null   int64
 5   5       3772 non-null   int64
 6   6       3772 non-null   int64
 7   7       3772 non-null   int64
 8   8       3772 non-null   int64
 9   9       3772 non-null   int64
 10  10      3772 non-null   int64
 11  11      3772 non-null   int64
 12  12      3772 non-null   int64
 13  13      3772 non-null   int64
 14  14      3772 non-null   int64
 15  15      3772 non-null   int64
 16  16      3772 non-null   float64
 17  17      3772 non-null   float64
 18  18      3772 non-null   float64
 19  19      3772 non-null   float64
 20  20      3772 non-null   float64
 21  21      3772 non-null   int64
dtypes: float64(6), int64(16)
memory usage: 648.4 KB

In [48]:
X_thyroid.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.73,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0.00060,0.015,0.120,0.082,0.146,3
1,0.24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.00025,0.030,0.143,0.133,0.108,3
2,0.47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.00190,0.024,0.102,0.131,0.078,3
3,0.64,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0.00090,0.017,0.077,0.090,0.085,3
4,0.23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.00025,0.026,0.139,0.090,0.153,3

In [49]:
Y_thyroid

0       3
1       3
2       3
3       3
4       3
       ..
3767    3
3768    3
3769    2
3770    3
3771    3
Name: 21, Length: 3772, dtype: int64

In [50]:
Y_thyroid=Y_thyroid.where(Y_thyroid==1, 0)

In [51]:
Y_thyroid.value_counts()

21
0    3679
1      93
Name: count, dtype: int64

Insight: Severe class imbalance ~ 2.5% of anomalous data

In [52]:
X_normal = X_thyroid[Y_thyroid==0].drop(X_thyroid.columns[-1], axis=1)
Y_normal = Y_thyroid[Y_thyroid==0]

X_hyperthyroids = X_thyroid[Y_thyroid == 1].drop(X_thyroid.columns[-1], axis=1)
Y_hyperthyroids = Y_thyroid[Y_thyroid == 1]

X_train_full, X_test, Y_train_full, Y_test = train_test_split(X_normal, Y_normal, test_size=0.2, random_state=42)
X_hyperthyroids_train, X_hyperthyroids_test, Y_hyperthyroids_train, Y_hyperthyroids_test = train_test_split(X_hyperthyroids, Y_hyperthyroids, test_size=0.2, random_state=42)
X_test = pandas.concat([X_test, X_hyperthyroids_test], ignore_index=True)
Y_test = pandas.concat([Y_test, Y_hyperthyroids_test], ignore_index=True)

X_train, X_validate, Y_train, Y_validate = train_test_split(X_train_full, Y_train_full, test_size=0.2, random_state=42)
X_validate = pandas.concat([X_validate, X_hyperthyroids_train], ignore_index=True)
Y_validate = pandas.concat([Y_validate, Y_hyperthyroids_train], ignore_index=True)

In [44]:
X_normal

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.73,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0.00060,0.0150,0.120,0.082,0.146
1,0.24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00025,0.0300,0.143,0.133,0.108
2,0.47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00190,0.0240,0.102,0.131,0.078
3,0.64,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00090,0.0170,0.077,0.090,0.085
4,0.23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00025,0.0260,0.139,0.090,0.153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3767,0.77,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00006,0.0206,0.125,0.107,0.117
3768,0.41,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00130,0.0250,0.125,0.114,0.109
3769,0.88,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.01300,0.0174,0.123,0.099,0.124
3770,0.64,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00078,0.0206,0.106,0.088,0.121
3771,0.46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00189,0.0206,0.093,0.091,0.102

# OC_SVM from Sklearn: Anomaly Detection

In [53]:
oc_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", OneClassSVM(kernel='rbf', gamma=0.01, nu=0.001))
])
oc_svm_clf.fit(X_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', OneClassSVM(gamma=0.01, nu=0.001))])

In [54]:
def output_formatter(predictions):
    predictions = np.where(predictions == 1, 0, 1)
    return predictions

In [55]:
predictions = output_formatter(oc_svm_clf.predict(X_validate))

In [56]:
Y_validate

0      0
1      0
2      0
3      0
4      0
      ..
658    1
659    1
660    1
661    1
662    1
Name: 21, Length: 663, dtype: int64

In [57]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1])

In [58]:
precision_score(Y_validate, predictions)

0.7307692307692307

In [59]:
recall_score(Y_validate, predictions)

0.5135135135135135

In [60]:
f1_score(Y_validate, predictions)

0.6031746031746031

Fine Tuning  

Scores = [(precision, recall, f1), ...]

In [61]:
from sklearn.model_selection import KFold
from itertools import product
gammas = ['scale', 'auto', 0.1, 0.001, 0.0001]
nus = [0.0001, 0.0005, 0.001, 0.01, 0.1]
models = []
avg_scores = []
kfold = KFold(n_splits=3, shuffle=True, random_state=42)
for (nu, gamma) in product(nus, gammas):
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", OneClassSVM(kernel='rbf', gamma=gamma, nu=nu))
    ])
    models.append(model)
    p, r, f1=0,0,0
    for train_i, test_i in kfold.split(X_train_full):
        X_train_fold, X_test_fold = X_train_full.iloc[train_i], X_train_full.iloc[test_i]
        Y_train_fold, Y_test_fold = Y_train_full.iloc[train_i], Y_train_full.iloc[test_i]
        
        # Validate set to contain the anomalies
        X_test_fold = pandas.concat([X_test_fold, X_hyperthyroids_train], ignore_index=True)
        Y_test_fold = pandas.concat([Y_test_fold, Y_hyperthyroids_train], ignore_index=True)
        
        model.fit(X_train_fold)
        predictions = output_formatter(model.predict(X_test_fold))
        p += precision_score(Y_test_fold, predictions)
        r += recall_score(Y_test_fold, predictions)
        f1 += f1_score(Y_test_fold, predictions)
    
    avg_scores.append((p/3, r/3, f1/3))

avg_scores = np.array(avg_scores)

In [62]:
len(models)

25

In [63]:
avg_scores

array([[0.39913804, 0.88738739, 0.54966955],
       [0.41964524, 0.8963964 , 0.57088477],
       [0.17628065, 0.95945946, 0.29690631],
       [0.78869048, 0.2027027 , 0.32163743],
       [0.85026738, 0.2027027 , 0.32603476],
       [0.45348271, 0.86486486, 0.59435562],
       [0.45929773, 0.85135135, 0.59603169],
       [0.34452495, 0.91441441, 0.49976112],
       [0.80059524, 0.2027027 , 0.32275725],
       [0.82142857, 0.1981982 , 0.31770674],
       [0.45243645, 0.85585586, 0.59146823],
       [0.46299513, 0.85585586, 0.60018148],
       [0.34940902, 0.91441441, 0.50482982],
       [0.78869048, 0.2027027 , 0.32163743],
       [0.82142857, 0.1981982 , 0.31770674],
       [0.45831896, 0.86486486, 0.59869121],
       [0.46431083, 0.85585586, 0.60122802],
       [0.34539955, 0.91441441, 0.50077615],
       [0.75847962, 0.40540541, 0.52521854],
       [0.75138079, 0.38738739, 0.5096455 ],
       [0.36558633, 0.87387387, 0.51472021],
       [0.36925849, 0.87387387, 0.51851364],
       [0.3353627 , 0.91441441, 0.48990723],
       [0.35930585, 0.74774775, 0.48521897],
       [0.35731647, 0.73873874, 0.48152818]])

In [64]:
indices_promising_models = np.where(avg_scores[:,2]>0.6)[0]
avg_scores[avg_scores[:,2]>.6]

array([[0.46299513, 0.85585586, 0.60018148],
       [0.46431083, 0.85585586, 0.60122802]])

In [65]:
promising_models = [models[i] for i in indices_promising_models]

In [66]:
for model in promising_models:
    predictions = output_formatter(model.predict(X_validate))
    print(precision_score(Y_validate, predictions), recall_score(Y_validate, predictions), f1_score(Y_validate, predictions))

0.7126436781609196 0.8378378378378378 0.7701863354037267
0.7045454545454546 0.8378378378378378 0.7654320987654321

**Testing against test set**

In [67]:
for model in promising_models:
    predictions = output_formatter(model.predict(X_test))
    print(precision_score(Y_test, predictions), recall_score(
        Y_test, predictions), f1_score(Y_test, predictions))

0.2073170731707317 0.8947368421052632 0.33663366336633666
0.20987654320987653 0.8947368421052632 0.34

Performance significantly diminished, probably due to the unseen data in test set

Because of the existence of test set, we're gonna train on the full training set (only normal data)

In [68]:
X_normal = X_thyroid[Y_thyroid == 0].drop(X_thyroid.columns[-1], axis=1)
X_normal

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.73,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0.00060,0.0150,0.120,0.082,0.146
1,0.24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00025,0.0300,0.143,0.133,0.108
2,0.47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00190,0.0240,0.102,0.131,0.078
3,0.64,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00090,0.0170,0.077,0.090,0.085
4,0.23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00025,0.0260,0.139,0.090,0.153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3767,0.77,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00006,0.0206,0.125,0.107,0.117
3768,0.41,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00130,0.0250,0.125,0.114,0.109
3769,0.88,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.01300,0.0174,0.123,0.099,0.124
3770,0.64,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00078,0.0206,0.106,0.088,0.121
3771,0.46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00189,0.0206,0.093,0.091,0.102

In [69]:
X_thyroid_test, Y_thyroid_test = helpers.load_thyroid_testset()
Y_thyroid_test = Y_thyroid_test.where(Y_thyroid_test == 1, 0)
X_thyroid_test = X_thyroid_test.drop(X_thyroid_test.columns[-1], axis=1)

In [70]:
Y_thyroid_test.value_counts()

21
0    3355
1      73
Name: count, dtype: int64

In [71]:
X_thyroid_test.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.0061,0.028,0.111,0.131,0.085
1,0.32,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.0013,0.019,0.084,0.078,0.107
2,0.35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.0000,0.031,0.239,0.100,0.239
3,0.21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.0010,0.018,0.087,0.088,0.099
4,0.22,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0.0004,0.022,0.134,0.135,0.099

In [72]:
from itertools import product
gammas = ['scale', 'auto', 0.1, 0.001, 0.0001]
nus = [0.0001, 0.0005, 0.001, 0.01, 0.1]
models = []
scores = []
for (nu, gamma) in product(nus, gammas):
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", OneClassSVM(kernel='rbf', gamma=gamma, nu=nu))
    ])
    models.append(model)
    model.fit(X_normal)
    predictions = output_formatter(model.predict(X_thyroid_test))
    scores.append((precision_score(Y_thyroid_test, predictions), recall_score(
        Y_thyroid_test, predictions), f1_score(Y_thyroid_test, predictions)))
scores = np.array(scores)

In [73]:
scores

array([[0.175     , 0.8630137 , 0.29099307],
       [0.175     , 0.8630137 , 0.29099307],
       [0.10806452, 0.91780822, 0.19336219],
       [0.45945946, 0.23287671, 0.30909091],
       [0.45714286, 0.21917808, 0.2962963 ],
       [0.1875    , 0.82191781, 0.30534351],
       [0.1875    , 0.82191781, 0.30534351],
       [0.121673  , 0.87671233, 0.21368948],
       [0.45945946, 0.23287671, 0.30909091],
       [0.44444444, 0.21917808, 0.29357798],
       [0.18944099, 0.83561644, 0.30886076],
       [0.18944099, 0.83561644, 0.30886076],
       [0.12307692, 0.87671233, 0.2158516 ],
       [0.45945946, 0.23287671, 0.30909091],
       [0.45945946, 0.23287671, 0.30909091],
       [0.19003115, 0.83561644, 0.30964467],
       [0.19003115, 0.83561644, 0.30964467],
       [0.12307692, 0.87671233, 0.2158516 ],
       [0.36082474, 0.47945205, 0.41176471],
       [0.35106383, 0.45205479, 0.39520958],
       [0.11842105, 0.8630137 , 0.20826446],
       [0.11842105, 0.8630137 , 0.20826446],
       [0.10891089, 0.90410959, 0.19440353],
       [0.1214128 , 0.75342466, 0.20912548],
       [0.1214128 , 0.75342466, 0.20912548]])

In [74]:
# Get indices of the best 3 models
indices = np.argsort(scores[:, 2])[-3:][::-1]
indices

array([18, 19, 16])

Pick the 3 best models

In [75]:
promising_models = [models[i] for i in indices]
promising_models_scores = [scores[i] for i in indices]

In [76]:
promising_models_scores

[array([0.36082474, 0.47945205, 0.41176471]),
 array([0.35106383, 0.45205479, 0.39520958]),
 array([0.19003115, 0.83561644, 0.30964467])]

In [84]:
promising_prediction = output_formatter(promising_models[0].predict(X_thyroid_test))

In [108]:
confusion_matrix(Y_thyroid_test, promising_prediction)

array([[3293,   62],
       [  38,   35]])

Recall in the context of Anomaly Detection, Confusion Matrix

| TN, FP |
| FN, TP |

In the context of correct diagnosis of hyperthyroids, perhaps false positives would be as important as true positives as we may not want healthy patients to be misdiagnosed

# Isolation Forest: Anomaly detection with Scikit Isolation Forest

In [119]:
from sklearn.ensemble import IsolationForest

X_train, X_test, Y_train, Y_test = train_test_split(X_normal, Y_normal, test_size=0.2, random_state=42)
X_test_with_anomalies = pandas.concat([X_test, X_hyperthyroids], ignore_index=True)
Y_test_with_anomalies = pandas.concat([Y_test, Y_hyperthyroids], ignore_index=True)

In [120]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2943 entries, 1609 to 3255
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2943 non-null   float64
 1   1       2943 non-null   int64
 2   2       2943 non-null   int64
 3   3       2943 non-null   int64
 4   4       2943 non-null   int64
 5   5       2943 non-null   int64
 6   6       2943 non-null   int64
 7   7       2943 non-null   int64
 8   8       2943 non-null   int64
 9   9       2943 non-null   int64
 10  10      2943 non-null   int64
 11  11      2943 non-null   int64
 12  12      2943 non-null   int64
 13  13      2943 non-null   int64
 14  14      2943 non-null   int64
 15  15      2943 non-null   int64
 16  16      2943 non-null   float64
 17  17      2943 non-null   float64
 18  18      2943 non-null   float64
 19  19      2943 non-null   float64
 20  20      2943 non-null   float64
dtypes: float64(6), int64(15)
memory usage: 505.8 KB

In [121]:
Y_hyperthyroids.info()

<class 'pandas.core.series.Series'>
Index: 93 entries, 19 to 3679
Series name: 21
Non-Null Count  Dtype
--------------  -----
93 non-null     int64
dtypes: int64(1)
memory usage: 1.5 KB

In [122]:
X_hyperthyroids.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 19 to 3679
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       93 non-null     float64
 1   1       93 non-null     int64
 2   2       93 non-null     int64
 3   3       93 non-null     int64
 4   4       93 non-null     int64
 5   5       93 non-null     int64
 6   6       93 non-null     int64
 7   7       93 non-null     int64
 8   8       93 non-null     int64
 9   9       93 non-null     int64
 10  10      93 non-null     int64
 11  11      93 non-null     int64
 12  12      93 non-null     int64
 13  13      93 non-null     int64
 14  14      93 non-null     int64
 15  15      93 non-null     int64
 16  16      93 non-null     float64
 17  17      93 non-null     float64
 18  18      93 non-null     float64
 19  19      93 non-null     float64
 20  20      93 non-null     float64
dtypes: float64(6), int64(15)
memory usage: 16.0 KB

In [123]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2943 entries, 1609 to 3255
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2943 non-null   float64
 1   1       2943 non-null   int64
 2   2       2943 non-null   int64
 3   3       2943 non-null   int64
 4   4       2943 non-null   int64
 5   5       2943 non-null   int64
 6   6       2943 non-null   int64
 7   7       2943 non-null   int64
 8   8       2943 non-null   int64
 9   9       2943 non-null   int64
 10  10      2943 non-null   int64
 11  11      2943 non-null   int64
 12  12      2943 non-null   int64
 13  13      2943 non-null   int64
 14  14      2943 non-null   int64
 15  15      2943 non-null   int64
 16  16      2943 non-null   float64
 17  17      2943 non-null   float64
 18  18      2943 non-null   float64
 19  19      2943 non-null   float64
 20  20      2943 non-null   float64
dtypes: float64(6), int64(15)
memory usage: 505.8 KB

In [124]:
Y_train.info()

<class 'pandas.core.series.Series'>
Index: 2943 entries, 1609 to 3255
Series name: 21
Non-Null Count  Dtype
--------------  -----
2943 non-null   int64
dtypes: int64(1)
memory usage: 46.0 KB

In [ ]:
contanmination_factors = [float(len(Y_hyperthyroids) / len(Y_normal)), 0.01, 0.001]
num_itrees = [10,15,20]
max_samples = [64, 'auto', 128]
max_features = [3,4,5,6]

In [126]:
from itertools import product
models = []
avg_scores = []
random_states = [40, 50, 60]
for (contanmination_factor, n_tree, max_sample, max_feature) in product(contanmination_factors, num_itrees, max_samples, max_features):
    model = IsolationForest(n_estimators=n_tree, contamination=contanmination_factor,
                            max_samples=max_sample, max_features=max_feature, n_jobs=-1, random_state=42)
    p, r, f1 = 0, 0, 0
    models.append(model)
    for rs in random_states:
        X_trainset, X_validate, Y_trainset, Y_validate = train_test_split(
            X_train, Y_train, test_size=0.2, random_state=rs)
        X_validate_with_anomalies = pandas.concat(
            [X_trainset, X_hyperthyroids], ignore_index=True)
        Y_validate_with_anomalies = pandas.concat(
            [Y_trainset, Y_hyperthyroids], ignore_index=True)

        model.fit(X_trainset)
        predictions = output_formatter(
            model.predict(X_validate_with_anomalies))

        p += precision_score(Y_validate_with_anomalies, predictions)
        r += recall_score(Y_validate_with_anomalies, predictions)
        f1 += f1_score(Y_validate_with_anomalies, predictions)

    avg_scores.append(
        [p/len(random_states), r/len(random_states), f1/len(random_states)])

In [127]:
avg_scores = np.array(avg_scores)
avg_scores

array([[0.05722705, 0.03942652, 0.04668433],
       [0.28523416, 0.25806452, 0.27092699],
       [0.2668987 , 0.25806452, 0.26114098],
       [0.36022386, 0.40501792, 0.37935513],
       [0.08100192, 0.05734767, 0.06714441],
       [0.41420787, 0.46236559, 0.43631384],
       [0.28985993, 0.2688172 , 0.27850877],
       [0.3947903 , 0.46236559, 0.42336449],
       [0.07592204, 0.05376344, 0.06293194],
       [0.32278364, 0.31541219, 0.31833595],
       [0.27420242, 0.26164875, 0.26644961],
       [0.39159587, 0.4265233 , 0.40683693],
       [0.26345275, 0.23297491, 0.24714481],
       [0.53001969, 0.72759857, 0.61328671],
       [0.3281125 , 0.31541219, 0.32160846],
       [0.56624686, 0.84229391, 0.67675988],
       [0.48823349, 0.62365591, 0.54691249],
       [0.56093891, 0.82437276, 0.66759488],
       [0.49641663, 0.63799283, 0.55814767],
       [0.54986713, 0.7921147 , 0.64870742],
       [0.36580775, 0.37992832, 0.37198198],
       [0.51206816, 0.69175627, 0.58692985],
       [0.49710391, 0.63799283, 0.55877696],
       [0.57325654, 0.86738351, 0.69021496],
       [0.28840789, 0.28673835, 0.28539446],
       [0.52614575, 0.72043011, 0.60768453],
       [0.37030897, 0.39784946, 0.38168976],
       [0.5007692 , 0.66308244, 0.56890877],
       [0.53717617, 0.74910394, 0.62564935],
       [0.54299812, 0.76702509, 0.63580667],
       [0.49175824, 0.62724014, 0.55097131],
       [0.5073568 , 0.66666667, 0.57597205],
       [0.45314167, 0.55197133, 0.49590751],
       [0.51835026, 0.70609319, 0.59665958],
       [0.4694263 , 0.5734767 , 0.51598113],
       [0.52610961, 0.71684588, 0.60677986],
       [0.05230769, 0.01433692, 0.02250392],
       [0.26711712, 0.09677419, 0.14185366],
       [0.25006386, 0.10394265, 0.14543835],
       [0.40587419, 0.18996416, 0.25770606],
       [0.0760114 , 0.02150538, 0.03352087],
       [0.38499959, 0.16845878, 0.23348214],
       [0.15740741, 0.05017921, 0.076     ],
       [0.4117096 , 0.21146953, 0.27475649],
       [0.08831909, 0.02508961, 0.03907563],
       [0.31515152, 0.1218638 , 0.1754386 ],
       [0.23809524, 0.08243728, 0.12233232],
       [0.44532628, 0.21863799, 0.29149396],
       [0.29135954, 0.10752688, 0.15695238],
       [0.63527969, 0.46594982, 0.53495447],
       [0.27000407, 0.10394265, 0.14971591],
       [0.72744991, 0.69175627, 0.70859123],
       [0.5460263 , 0.32616487, 0.40584432],
       [0.6758658 , 0.5483871 , 0.60368322],
       [0.55767762, 0.34408602, 0.42269495],
       [0.69183136, 0.59498208, 0.63694529],
       [0.40548341, 0.17921147, 0.24822799],
       [0.58928483, 0.45878136, 0.50060748],
       [0.57816764, 0.35483871, 0.43958383],
       [0.70221137, 0.61648746, 0.65508382],
       [0.2590526 , 0.09318996, 0.1368214 ],
       [0.6038332 , 0.41218638, 0.48622038],
       [0.2996337 , 0.11469534, 0.16556957],
       [0.51309879, 0.29032258, 0.36758231],
       [0.6338286 , 0.47311828, 0.53681828],
       [0.61594779, 0.42293907, 0.49977624],
       [0.42645929, 0.23297491, 0.29637468],
       [0.56360821, 0.3655914 , 0.43938284],
       [0.39826295, 0.18637993, 0.25172726],
       [0.55572115, 0.40501792, 0.4579161 ],
       [0.43393009, 0.21146953, 0.28300903],
       [0.56005122, 0.35125448, 0.42802015],
       [0.        , 0.        , 0.        ],
       [0.13333333, 0.00716846, 0.01360544],
       [0.33333333, 0.01792115, 0.03394772],
       [0.63131313, 0.05017921, 0.09196378],
       [0.08333333, 0.00358423, 0.00687285],
       [0.3       , 0.01433692, 0.02735115],
       [0.        , 0.        , 0.        ],
       [0.5       , 0.03225806, 0.06060606],
       [0.16666667, 0.00716846, 0.0137457 ],
       [0.21666667, 0.01075269, 0.02047829],
       [0.21666667, 0.01075269, 0.02047829],
       [0.59047619, 0.05017921, 0.09217613],
       [0.40714286, 0.02508961, 0.04714496],
       [0.43333333, 0.02508961, 0.0474129 ],
       [0.32380952, 0.02150538, 0.04027211],
       [0.83333333, 0.18637993, 0.30014706],
       [0.41666667, 0.02508961, 0.04727689],
       [0.25      , 0.01433692, 0.02707487],
       [0.26666667, 0.01433692, 0.02721088],
       [0.71296296, 0.1218638 , 0.19933993],
       [0.5       , 0.03225806, 0.06060606],
       [0.41666667, 0.02508961, 0.04727689],
       [0.35      , 0.01792115, 0.03408374],
       [0.76547619, 0.18996416, 0.2862044 ],
       [0.3       , 0.01433692, 0.02735115],
       [0.29166667, 0.02150538, 0.03987615],
       [0.38333333, 0.02150538, 0.04068031],
       [0.62222222, 0.05734767, 0.10472515],
       [0.31666667, 0.02867384, 0.0521803 ],
       [0.08333333, 0.00358423, 0.00687285],
       [0.25      , 0.01433692, 0.02707487],
       [0.60714286, 0.05017921, 0.09267327],
       [0.55555556, 0.04301075, 0.07961973],
       [0.27380952, 0.01792115, 0.03353952],
       [0.44047619, 0.02867384, 0.05374154],
       [0.62797619, 0.07168459, 0.12637939]])

In [128]:
indices = np.argsort(avg_scores[:, 2])[-3:][::-1]
indices

array([51, 23, 15])

In [129]:
best_models = [models[i] for i in indices]
best_models

[IsolationForest(contamination=0.01, max_features=6, max_samples=64,
                 n_estimators=15, n_jobs=-1, random_state=42),
 IsolationForest(contamination=0.025278608317477577, max_features=6,
                 max_samples=128, n_estimators=15, n_jobs=-1, random_state=42),
 IsolationForest(contamination=0.025278608317477577, max_features=6,
                 max_samples=64, n_estimators=15, n_jobs=-1, random_state=42)]

In [130]:
best_if_model = best_models[0]

In [131]:
pred = output_formatter(best_if_model.predict(X_test_with_anomalies))
[precision_score(Y_test_with_anomalies, pred), recall_score(
    Y_test_with_anomalies, pred), f1_score(Y_test_with_anomalies, pred)]

[0.8987341772151899, 0.7634408602150538, 0.8255813953488372]

In [132]:
confusion_matrix(Y_test_with_anomalies, pred)

array([[728,   8],
       [ 22,  71]])

In [133]:
scores = []
for rs in range(1, 100):
    X_trainset, X_test, Y_trainset, Y_test = train_test_split(
        X_normal, Y_normal, test_size=0.2, random_state=rs)
    X_test_with_anomalies = pandas.concat(
        [X_test, X_hyperthyroids], ignore_index=True)
    Y_test_with_anomalies = pandas.concat(
        [Y_test, Y_hyperthyroids], ignore_index=True)
    best_if_model.fit(X_trainset)
    predictions = output_formatter(
        best_if_model.predict(X_test_with_anomalies))

    scores.append([precision_score(Y_test_with_anomalies, predictions), recall_score(
        Y_test_with_anomalies, predictions), f1_score(Y_test_with_anomalies, predictions)])

In [134]:
scores = np.array(scores)
np.mean(scores, axis=0)

array([0.87902203, 0.62126643, 0.71952331])

In [135]:
scores_feature_scaled = []
iso_forest = Pipeline([
    ("scaler", StandardScaler()),
    ("if_clf", best_if_model)
])
for rs in range(1, 100):
    X_trainset, X_validate, Y_trainset, Y_test = train_test_split(
        X_normal, Y_normal, test_size=0.2, random_state=rs)
    X_test_with_anomalies = pandas.concat(
        [X_test, X_hyperthyroids], ignore_index=True)
    Y_test_with_anomalies = pandas.concat(
        [Y_test, Y_hyperthyroids], ignore_index=True)
    iso_forest.fit(X_trainset)
    predictions = output_formatter(
        iso_forest.predict(X_test_with_anomalies))

    scores_feature_scaled.append([precision_score(Y_test_with_anomalies, predictions), recall_score(
        Y_test_with_anomalies, predictions), f1_score(Y_test_with_anomalies, predictions)])

In [136]:
scores_feature_scaled = np.array(scores_feature_scaled)
np.mean(scores_feature_scaled, axis=0)

array([0.89074217, 0.62126643, 0.72443971])

Conclusion: Scaled performance slightly worst

In [107]:
best_if_model.get_params()

{'bootstrap': False,
 'contamination': 0.01,
 'max_features': 6,
 'max_samples': 64,
 'n_estimators': 15,
 'n_jobs': -1,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

Current model performances:  
    - OC-SVM( ? ): F1_score ~ 0.41176471   
    - Isolation Forest ('contamination': 0.01, 'max_features': 6, 'max_samples': 64, 'n_estimators': 15, 'n_jobs': -1, ) : F1_score ~ 0.72443971

# Autoencoder: In the context of Anomaly Detection